---
- name: Template Kafka broker service unit
  ansible.builtin.template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    mode: "0644"
  notify:
    - reload systemd
    - restart kafka broker

- name: Create systemd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/kafka.service.d
    state: directory
    mode: "0755"

- name: Template systemd override
  ansible.builtin.template:
    src: override.conf.j2
    dest: /etc/systemd/system/kafka.service.d/override.conf
    mode: "0644"
  notify:
    - reload systemd
    - restart kafka broker

- name: Enable Kafka service
  ansible.builtin.systemd:
    name: kafka
    enabled: true
    daemon_reload: true
