---
galaxy_info:
  author: OSO DevOps
  description: TLS certificate generation for Kafka (CA, keystores, truststores)
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - kafka
    - ssl
    - tls
    - security
    - certificates
dependencies: []
